# Generated by Django 3.2.5 on 2021-08-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dojos_ninjas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='state',
            field=models.CharField(max_length=45),
        ),
    ]
