# Generated by Django 3.2.5 on 2021-08-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_authors_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default='notas antiguos', max_length=255),
        ),
    ]
